schema: workflow/2022.04
name: Ingest TikTok Trending
settings:
  error_notification: true
  lambda_memory: 2048
  lambda_timeout: 600
  network: net_5Lnie3
triggers:
- id: ti_NQT2GrW
steps:
- namespace: fetch_source
  runtime: nodejs20.x
  uses: "./fetch_source/entry.js"
- namespace: upsert_signals
  runtime: nodejs20.x
  uses: "./upsert_signals/entry.js"
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    target_table: STG_EXTERNAL_SIGNALS

