schema: workflow/2022.04
name: Gemini Prompt Tester
settings:
  error_notification: true
  lambda_memory: 1024
  lambda_timeout: 600
triggers:
- id: hi_35HVyD1
steps:
- namespace: fetch_source
  runtime: nodejs20.x
  uses: "./fetch_source/entry.js"
  props:
    google_gemini:
      authProvisionId: apn_EOhp9DY
