schema: workflow/2022.04
name: Ingest Pinterest
inactive: true
settings:
  error_notification: true
  lambda_memory: 1024
  lambda_timeout: 600
  network: net_5Lnie3
triggers:
- id: ti_1RTYWoY
steps:
- namespace: fetch_source
  runtime: nodejs20.x
  uses: "./fetch_source/entry.js"
- namespace: upsert_signals
  runtime: nodejs20.x
  uses: "./upsert_signals/entry.js"
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    target_table: STG_EXTERNAL_SIGNALS_TEST

