schema: workflow/2022.04
name: Error Alerts
settings:
  lambda_memory: 512
triggers:
- id: dc_zqug7mj
steps:
- namespace: normalize_error
  runtime: nodejs20.x
  uses: "./normalize_error/entry.js"
  props:
    trigger_event: "{{steps.trigger.event}}"
- namespace: post_to_slack
  runtime: nodejs20.x
  uses: slack_v2-send-message-to-channel@0.1.3
  props:
    slack:
      authProvisionId: apn_OghQ5eO
    text: "{{steps.normalize_error.$return_value.slack_text}}"
