schema: workflow/2022.04
name: Error Alerts
settings:
  lambda_memory: 512
triggers:
- id: dc_zqug7mj
steps:
- namespace: normalize_error
  runtime: nodejs20.x
  uses: "./normalize_error/entry.js"
  props:
    trigger_event: "{{steps.trigger.event}}"
- namespace: send_message
  runtime: nodejs20.x
  uses: slack_v2-send-message@0.1.3
  _props_cursor: dyp_zqUpAo61
  props:
    slack:
      authProvisionId: apn_arhlGm8
    channelType:
      __lv:
        label: User / Direct Message
        value: im
    conversation:
      __lv:
        label: 'Direct messaging with: Martin Mena'
        value: D092AG6TUC9
    text: "{{steps.normalize_error.$return_value.slack_text}}"
    as_user: true
    addToChannel: true
    thread_broadcast: false
    unfurl_links: false
    unfurl_media: false

