schema: workflow/2022.04
name: Enrichment Dispatcher
settings:
  error_notification: true
  lambda_memory: 2048
  lambda_timeout: 600
triggers:
- id: hi_KNH6klV
steps:
- namespace: normalize_event
  runtime: nodejs20.x
  uses: "./normalize_event/entry.js"
- namespace: orchestrate
  runtime: nodejs20.x
  uses: "./orchestrate/entry.js"
  props:
    trend_id: "{{steps.normalize_event.$return_value.trend_id}}"
    enrichment_type: "{{steps.normalize_event.$return_value.enrichment_type}}"
    trend_event: "{{steps.trigger.event}}"
- namespace: respond
  runtime: nodejs20.x
  uses: "./respond/entry.js"
  props:
    orchestrate_output: "{{steps.orchestrate.$return_value}}"
