schema: workflow/2022.04
name: Prediction Agent
settings:
  error_notification: true
  lambda_memory: 4096
  lambda_timeout: 600
triggers:
- id: hi_a1H4aWR
- id: dc_wDuPeGB
steps:
- namespace: normalize_event
  runtime: nodejs20.x
  uses: "./normalize_event/entry.mjs"
  props:
    trigger_event: "{{steps.trigger.event}}"
- namespace: commit_to_ledger
  runtime: nodejs20.x
  uses: "./commit_to_ledger/entry.mjs"
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    chain_id: "{{steps.normalize_event.$return_value.chain_id}}"
    dry_run: "{{steps.normalize_event.$return_value.dry_run}}"
- namespace: summarize
  runtime: nodejs20.x
  uses: "./summarize/entry.mjs"
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    chain_id: "{{steps.normalize_event.$return_value.chain_id}}"
- namespace: respond
  runtime: nodejs20.x
  uses: "./respond/entry.mjs"
  props:
    event: "{{steps.normalize_event.$return_value}}"
    summary: "{{steps.summarize.$return_value}}"
    commit_result: "{{steps.commit_to_ledger.$return_value}}"
