schema: workflow/2022.04
name: Ingest Bluesky
settings:
  error_notification: true
  lambda_memory: 1024
  lambda_timeout: 600
  network: net_5Lnie3
triggers:
- id: ti_rrTAJ2X
steps:
- namespace: fetch_source
  runtime: nodejs20.x
  uses: "./fetch_source/entry.js"
  props:
    bluesky: {}
- namespace: upsert_signals
  runtime: nodejs20.x
  uses: snowflake-execute-sql-query@0.2.3
  props:
    snowflake:
      authProvisionId: apn_yghdQYJ
    sql:
      value: |-
        CALL MCC_RAW.MARKETING_DEV.MERGE_EXTERNAL_SIGNALS(:1, '', 500, 'STG_EXTERNAL_SIGNALS_TEST')
      query: |-
        CALL MCC_RAW.MARKETING_DEV.MERGE_EXTERNAL_SIGNALS(:1, '', 500, 'STG_EXTERNAL_SIGNALS_TEST')
    params:
    - "{{steps.fetch_source.$return_value.signals_json}}"

