-- One-time backfill: populate FCT_SIGNALS from existing STG_EXTERNAL_SIGNALS
-- so cluster procs and the new q_cluster_signals step have data on day one.
-- Same body as TASK_PROMOTE_SIGNALS_TO_FCT — runs immediately, then the
-- recurring TASK takes over.
--
-- Idempotent (NOT EXISTS guard); safe to re-run.

INSERT INTO MCC_PRESENTATION.TREND_AGENT.FCT_SIGNALS
    (SIGNAL_ID, SOURCE_NAME, SIGNAL_TIMESTAMP, SIGNAL_TITLE, SIGNAL_TEXT,
     METADATA, SIGNAL_VECTOR)
SELECT
    s.SIGNAL_ID, s.SOURCE_NAME, s.SIGNAL_TIMESTAMP,
    s.SIGNAL_TITLE, s.SIGNAL_TEXT, s.METADATA,
    SNOWFLAKE.CORTEX.EMBED_TEXT_1024(
        'snowflake-arctic-embed-l-v2.0',
        s.SIGNAL_TITLE || ' ' || LEFT(COALESCE(s.SIGNAL_TEXT, ''), 512)
    )
FROM MCC_RAW.MARKETING_DEV.STG_EXTERNAL_SIGNALS s
WHERE s.SIGNAL_TITLE IS NOT NULL
  AND s.SOURCE_NAME != 'amazon_movers'
  AND s.SIGNAL_TIMESTAMP >= DATEADD(day, -3, CURRENT_TIMESTAMP())
  AND NOT EXISTS (
      SELECT 1 FROM MCC_PRESENTATION.TREND_AGENT.FCT_SIGNALS f
      WHERE f.SIGNAL_ID = s.SIGNAL_ID
  )
QUALIFY ROW_NUMBER() OVER (PARTITION BY s.SIGNAL_ID ORDER BY s.INGESTED_AT ASC) = 1;

-- Verification
SELECT
  (SELECT COUNT(*) FROM MCC_PRESENTATION.TREND_AGENT.FCT_SIGNALS)         AS FCT_TOTAL,
  (SELECT COUNT(*) FROM MCC_PRESENTATION.TREND_AGENT.FCT_SIGNALS
    WHERE SIGNAL_VECTOR IS NULL)                                          AS FCT_MISSING_VECTORS,
  (SELECT COUNT(DISTINCT SIGNAL_ID) FROM MCC_RAW.MARKETING_DEV.STG_EXTERNAL_SIGNALS
    WHERE SIGNAL_TIMESTAMP >= DATEADD(day, -3, CURRENT_TIMESTAMP())
      AND SIGNAL_TITLE IS NOT NULL
      AND SOURCE_NAME != 'amazon_movers')                                 AS STG_ELIGIBLE_3D;
