-- Backfill: insert PROMOTE_NEW rows into FCT_PROMOTION_LEDGER for trends that
-- were promoted before the ledger was introduced (2026-04-28). One row per
-- promoted candidate that doesn't already have a ledger entry.
--
-- After this runs, every row in FCT_TRENDS has a corresponding ledger row,
-- which lets DT_TREND_DASHBOARD source TOTAL_CLUSTER_SIZE and
-- DISTINCT_SOURCE_COUNT from FCT_PROMOTION_LEDGER instead of reaching
-- cross-database into MCC_RAW.MARKETING_DEV.STG_TREND_CANDIDATES.

INSERT INTO MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_LEDGER
  (CANDIDATE_ID, CHAIN_ID, ITERATION, DECIDED_AT,
   DECISION, DECISION_CATEGORY, TARGET_TREND_ID,
   DISTILLATION_VERDICT, OVERRODE_VERDICT,
   MAX_NEIGHBOR_SIM, CONSIDERED_NEIGHBORS,
   CLUSTER_SIZE, SOURCE_COUNT, CONFIDENCE,
   RATIONALE, MODEL_USED, INPUT_TOKENS, OUTPUT_TOKENS, COST_ESTIMATE)
SELECT
  c.CANDIDATE_ID,
  COALESCE(c.PROMOTION_DECIDED_BY, c.CHAIN_ID, 'backfill-2026-04-28'),
  COALESCE(c.ITERATION, 1),
  c.PROMOTED_AT,
  CASE WHEN c.DEDUP_OF_TREND_ID IS NOT NULL THEN 'MERGE_INTO_EXISTING' ELSE 'PROMOTE_NEW' END,
  'BACKFILL',
  COALESCE(c.PROMOTED_TO, c.DEDUP_OF_TREND_ID),
  c.VERDICT,
  FALSE,
  NULL,
  NULL,
  ARRAY_SIZE(c.SUPPORTING_SIGNAL_IDS),
  ARRAY_SIZE(OBJECT_KEYS(c.SOURCE_BREAKDOWN)),
  c.CONFIDENCE,
  LEFT(COALESCE(c.REASONING, 'backfill from STG_TREND_CANDIDATES'), 4000),
  'backfill',
  NULL, NULL, NULL
FROM MCC_RAW.MARKETING_DEV.STG_TREND_CANDIDATES c
JOIN MCC_PRESENTATION.TREND_AGENT.FCT_TRENDS t
  ON COALESCE(c.PROMOTED_TO, c.DEDUP_OF_TREND_ID) = t.TREND_ID
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_LEDGER pl
  ON pl.CANDIDATE_ID = c.CANDIDATE_ID
WHERE c.PROMOTED_AT IS NOT NULL
  AND pl.CANDIDATE_ID IS NULL;
