-- Fact: Core trend metrics — one row per trend cluster
-- Database: MCC_PRESENTATION.TREND_AGENT

create or replace table MCC_PRESENTATION.TREND_AGENT.FCT_TREND_METRICS (
    TREND_ID VARCHAR(16777216) NOT NULL,
    TREND_VECTOR VECTOR(FLOAT, 1024),
    TREND_TOPIC VARCHAR(16777216),
    DETECTED_AT TIMESTAMP_NTZ(9),
    LAST_UPDATE_AT TIMESTAMP_NTZ(9),
    TREND_DURATION_HR FLOAT,
    TOTAL_CLUSTER_SIZE NUMBER(38,0),
    SIGNAL_CHANGE FLOAT,
    DISTINCT_SOURCE_COUNT NUMBER(38,0),
    AVG_SIMILARITY FLOAT,
    VELOCITY_DIRECTION VARCHAR(16777216),
    SIGNALS_PER_SOURCE FLOAT,
    TREND_HEAT_INDEX FLOAT,
    PARENT_TREND_ID VARCHAR(16777216),       -- FK to self; set when trend was split from a parent. NOT NULL = superseded.
    primary key (TREND_ID)
);

-- Migration (run once against existing table):
-- ALTER TABLE MCC_PRESENTATION.TREND_AGENT.FCT_TREND_METRICS ADD COLUMN PARENT_TREND_ID VARCHAR;
