-- Fact: Daily signal/source counts per trend for velocity tracking
-- Database: MCC_PRESENTATION.TREND_AGENT

create or replace table MCC_PRESENTATION.TREND_AGENT.FCT_TREND_DAILY_SNAPSHOTS (
    TREND_ID VARCHAR(16777216) NOT NULL,
    SNAPSHOT_DATE DATE NOT NULL,
    SIGNAL_COUNT NUMBER(38,0),
    SOURCE_COUNT NUMBER(38,0),
    NEW_SIGNALS_TODAY NUMBER(38,0),
    NEW_SOURCES_TODAY NUMBER(38,0),
    primary key (TREND_ID, SNAPSHOT_DATE)
);
