-- Staging: Google Trends ingestion
-- Database: MCC_RAW.MARKETING_DEV

create or replace table MCC_RAW.MARKETING_DEV.STG_GOOGLE_TRENDS (
    TREND_ID NUMBER DEFAULT MCC_RAW.MARKETING_DEV.SEQ_GOOGLE_TRENDS_ID.NEXTVAL,
    TREND_TITLE VARCHAR(16777216),
    APPROX_TRAFFIC VARCHAR(16777216),
    PUB_DATE TIMESTAMP_NTZ(9),
    NEWS_ITEMS VARIANT,
    INSERTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Google Trends daily trending searches + related queries. TREND_ID auto-assigned by sequence.';
