-- Staging: LLM prompt/response audit log
-- Database: MCC_RAW.MARKETING_DEV

create or replace table MCC_RAW.MARKETING_DEV.STG_LLM_PROMPT_LOGS (
    INGESTION_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder
        COMMENT 'Unique identifier for the ingestion of the model.',
    CREATED_AT_UTC TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'Timestamp when the model was created in UTC.',
    MODEL_NAME VARCHAR(100)
        COMMENT 'Name of the model used.',
    PROVIDER VARCHAR(50)
        COMMENT 'Provider of the model.',
    PROMPT_TOKENS NUMBER(38,0)
        COMMENT 'Number of tokens in the model''s prompt.',
    COMPLETION_TOKENS NUMBER(38,0)
        COMMENT 'Number of tokens in the model''s completion.',
    TOTAL_TOKENS NUMBER(38,0)
        COMMENT 'Total number of tokens in the model''s output.',
    LATENCY_MS NUMBER(38,0)
        COMMENT 'Time taken by the model to complete in milliseconds.',
    PROMPT VARIANT
        COMMENT 'Input prompt used to generate the model''s response.',
    RESPONSE VARIANT
        COMMENT 'Model''s response to the input prompt.',
    USAGE_CONTEXT VARCHAR(255)
        COMMENT 'Context in which the model was used.',
    METADATA VARIANT
        COMMENT 'Metadata associated with the model, such as web search count or citation count.'
) COMMENT = 'The table contains records of model usage logs, specifically logs of prompts and responses generated by a language model.';
