-- Twin-create FCT_PROMOTION_LEDGER from FCT_PROMOTION_AUDIT.
-- Same schema, same data at creation time. PROC_PROMOTION_APPLY v3 writes
-- to LEDGER only; AUDIT gets dropped in step 6.
--
-- The transition window (between this twin creation and the v3 PROC deploy)
-- writes new rows to AUDIT only. We re-sync at step 6 just before dropping.

CREATE TABLE IF NOT EXISTS MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_LEDGER
  LIKE MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_AUDIT;

INSERT INTO MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_LEDGER
SELECT * FROM MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_AUDIT
WHERE NOT EXISTS (
  SELECT 1 FROM MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_LEDGER l
  WHERE l.AUDIT_ID = MCC_PRESENTATION.TREND_AGENT.FCT_PROMOTION_AUDIT.AUDIT_ID
);
