-- Twin-create FCT_TREND_LIFECYCLE_LEDGER from FCT_TREND_LIFECYCLE_HISTORY.
-- Same schema, same data at creation time. PROC_LIFECYCLE_APPLY v3 writes
-- to LEDGER only; HISTORY gets dropped in step 6.

CREATE TABLE IF NOT EXISTS MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_LEDGER
  LIKE MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_HISTORY;

INSERT INTO MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_LEDGER
SELECT * FROM MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_HISTORY
WHERE NOT EXISTS (
  SELECT 1 FROM MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_LEDGER l
  WHERE l.LIFECYCLE_EVAL_ID = MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_HISTORY.LIFECYCLE_EVAL_ID
);
