-- URL validation audit log
-- Database: MCC_RAW.MARKETING_DEV
-- Populated by: scripts/url_audit.py

CREATE TABLE IF NOT EXISTS MCC_RAW.MARKETING_DEV.URL_VALIDATION_LOG (
    URL              VARCHAR NOT NULL,
    DOMAIN           VARCHAR,
    SOURCE_NAME      VARCHAR,
    SIGNAL_TYPE      VARCHAR(10),
    HTTP_STATUS      NUMBER,
    IS_REACHABLE     BOOLEAN,
    RESPONSE_TIME_MS NUMBER,
    CONTENT_TYPE     VARCHAR,
    REDIRECT_URL     VARCHAR,
    ERROR_MESSAGE    VARCHAR,
    TITLE_EXTRACTED  VARCHAR(1000),
    CONTENT_SNIPPET  VARCHAR(4000),
    REPAIR_STATUS    VARCHAR(20),
    CORRECTED_URL    VARCHAR,
    REPAIR_CONFIDENCE VARCHAR(10),
    REPAIR_REASONING VARCHAR(500),
    CHECKED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
