-- View: derived per-trend aggregates from STG_TREND_CANDIDATES.
-- Replaces TOTAL_CLUSTER_SIZE + DISTINCT_SOURCE_COUNT that used to be cached
-- on FCT_TRENDS and recomputed by PROC_PROMOTION_APPLY's MERGE_INTO_EXISTING
-- branch. Now derived in one place at query time.

CREATE OR REPLACE VIEW MCC_PRESENTATION.TREND_AGENT.V_TREND_AGGREGATES AS
WITH trend_candidates AS (
  SELECT t.TREND_ID, c.SUPPORTING_SIGNAL_IDS, c.SOURCE_BREAKDOWN
  FROM MCC_PRESENTATION.TREND_AGENT.FCT_TRENDS t
  JOIN MCC_RAW.MARKETING_DEV.STG_TREND_CANDIDATES c
    ON c.CANDIDATE_ID = t.CANDIDATE_ID
    OR c.DEDUP_OF_TREND_ID = t.TREND_ID
),
sigs AS (
  SELECT TREND_ID, COUNT(DISTINCT f.value::STRING) AS TOTAL_CLUSTER_SIZE
  FROM trend_candidates,
       LATERAL FLATTEN(INPUT => SUPPORTING_SIGNAL_IDS) f
  GROUP BY TREND_ID
),
srcs AS (
  SELECT TREND_ID, COUNT(DISTINCT k.value::STRING) AS DISTINCT_SOURCE_COUNT
  FROM trend_candidates,
       LATERAL FLATTEN(INPUT => OBJECT_KEYS(SOURCE_BREAKDOWN)) k
  GROUP BY TREND_ID
)
SELECT
  t.TREND_ID,
  COALESCE(sigs.TOTAL_CLUSTER_SIZE,    0) AS TOTAL_CLUSTER_SIZE,
  COALESCE(srcs.DISTINCT_SOURCE_COUNT, 0) AS DISTINCT_SOURCE_COUNT
FROM MCC_PRESENTATION.TREND_AGENT.FCT_TRENDS t
LEFT JOIN sigs ON sigs.TREND_ID = t.TREND_ID
LEFT JOIN srcs ON srcs.TREND_ID = t.TREND_ID;
