-- View: latest lifecycle decision per trend.
-- Surfaces what FCT_TRENDS used to expose directly (LIFECYCLE_STATUS, HEAT_INDEX, etc).
-- Computed at query time (cheap at our scale; revisit if the ledger grows past ~100K rows).

CREATE OR REPLACE VIEW MCC_PRESENTATION.TREND_AGENT.V_TREND_LIFECYCLE_CURRENT AS
WITH ranked AS (
  SELECT
    TREND_ID,
    EVALUATED_AT,
    NEW_STATUS                AS LIFECYCLE_STATUS,
    NEW_HEAT                  AS HEAT_INDEX,
    NEW_HEAT_SMOOTHED         AS HEAT_INDEX_SMOOTHED,
    NEXT_EVAL_AT,
    REASONING                 AS LAST_REASONING,
    DECISION_PAYLOAD,
    REQUESTED_RE_ENRICHMENT,
    AGENT_SESSION_ID,
    CHAIN_ID,
    ROW_NUMBER() OVER (PARTITION BY TREND_ID ORDER BY EVALUATED_AT DESC) AS rn
  FROM MCC_PRESENTATION.TREND_AGENT.FCT_TREND_LIFECYCLE_LEDGER
)
SELECT
  TREND_ID,
  LIFECYCLE_STATUS,
  HEAT_INDEX,
  HEAT_INDEX_SMOOTHED,
  EVALUATED_AT              AS LAST_EVAL_AT,
  NEXT_EVAL_AT,
  LAST_REASONING,
  DECISION_PAYLOAD:retirement_reason::STRING AS RETIREMENT_REASON,
  REQUESTED_RE_ENRICHMENT,
  AGENT_SESSION_ID          AS LAST_AGENT_SESSION_ID,
  CHAIN_ID                  AS LAST_CHAIN_ID
FROM ranked
WHERE rn = 1;
