-- View: Lightweight diagnostic over trend lifecycle state.
-- Database: MCC_PRESENTATION.TREND_AGENT
--
-- 2026-04-28 (refactor): refactored to read from V_TREND_LIFECYCLE_CURRENT
-- and V_TREND_AGGREGATES + FCT_TRENDS (identity only). DIM_TREND_ENRICHMENT
-- replaced by V_TREND_ENRICHMENT_CURRENT.
--
-- This view exists for ops visibility only. The lifecycle agent does NOT
-- consume it — it computes its own decisions per the prompts in
-- DIM_LLM_PROMPT.

CREATE OR REPLACE VIEW MCC_PRESENTATION.TREND_AGENT.V_TREND_LIFECYCLE AS
WITH source_summary AS (
    SELECT
        TREND_ID,
        COUNT(*)         AS SOURCE_COVERAGE_BREADTH,
        MAX(ENRICHED_AT) AS SOURCES_ENRICHED_AT
    FROM MCC_PRESENTATION.TREND_AGENT.FCT_TREND_SOURCE_METRICS
    WHERE HEADLINE_METRIC IS NOT NULL AND HEADLINE_METRIC > 0
    GROUP BY TREND_ID
)
SELECT
    t.TREND_ID,
    COALESCE(t.TREND_NAME_B2B, t.TREND_TOPIC)                AS TREND_NAME,
    lc.LIFECYCLE_STATUS,
    ROUND(COALESCE(lc.HEAT_INDEX_SMOOTHED, lc.HEAT_INDEX), 1) AS HEAT_INDEX,
    agg.TOTAL_CLUSTER_SIZE,
    agg.DISTINCT_SOURCE_COUNT,

    t.PROMOTED_AT,
    t.LAST_UPDATE_AT,
    lc.LAST_EVAL_AT                                          AS LAST_LIFECYCLE_EVAL_AT,
    lc.NEXT_EVAL_AT                                          AS NEXT_LIFECYCLE_EVAL_AT,
    lc.RETIREMENT_REASON,

    e.ENRICHED_AT,
    e.ENRICHMENT_VERSION,
    COALESCE(ss.SOURCE_COVERAGE_BREADTH, 0)                  AS SOURCE_COVERAGE_BREADTH,
    ss.SOURCES_ENRICHED_AT,

    DATEDIFF('hour', t.PROMOTED_AT,        CURRENT_TIMESTAMP()) AS AGE_HOURS,
    DATEDIFF('hour', t.LAST_UPDATE_AT,     CURRENT_TIMESTAMP()) AS HOURS_SINCE_UPDATE,
    DATEDIFF('hour', e.ENRICHED_AT,        CURRENT_TIMESTAMP()) AS HOURS_SINCE_ENRICHMENT,
    DATEDIFF('hour', lc.LAST_EVAL_AT,      CURRENT_TIMESTAMP()) AS HOURS_SINCE_LIFECYCLE_EVAL,
    DATEDIFF('hour', ss.SOURCES_ENRICHED_AT, CURRENT_TIMESTAMP()) AS HOURS_SINCE_SOURCE_REFRESH,

    CASE
        WHEN lc.LIFECYCLE_STATUS = 'RETIRED'
            THEN 'RETIRED'

        WHEN e.ENRICHED_AT IS NULL AND COALESCE(agg.TOTAL_CLUSTER_SIZE, 0) >= 3
            THEN 'NEEDS_ENRICHMENT'

        WHEN lc.NEXT_EVAL_AT IS NOT NULL
             AND lc.NEXT_EVAL_AT <= CURRENT_TIMESTAMP()
            THEN 'LIFECYCLE_DUE'

        WHEN COALESCE(lc.HEAT_INDEX, 0) >= 50
             AND DATEDIFF('hour', e.ENRICHED_AT, CURRENT_TIMESTAMP()) > 48
            THEN 'NEEDS_REFRESH'

        WHEN DATEDIFF('hour', ss.SOURCES_ENRICHED_AT, CURRENT_TIMESTAMP()) > 24
             AND DATEDIFF('hour', t.LAST_UPDATE_AT, CURRENT_TIMESTAMP()) < 24
            THEN 'SOURCES_STALE'

        ELSE 'OK'
    END                                                       AS ACTION_NEEDED

FROM MCC_PRESENTATION.TREND_AGENT.FCT_TRENDS t
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.V_TREND_LIFECYCLE_CURRENT  lc  ON lc.TREND_ID  = t.TREND_ID
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.V_TREND_ENRICHMENT_CURRENT e   ON e.TREND_ID   = t.TREND_ID
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.V_TREND_AGGREGATES         agg ON agg.TREND_ID = t.TREND_ID
LEFT JOIN source_summary ss
       ON t.TREND_ID = ss.TREND_ID
ORDER BY
    CASE WHEN lc.LIFECYCLE_STATUS = 'RETIRED' THEN 1 ELSE 0 END,
    COALESCE(lc.HEAT_INDEX_SMOOTHED, lc.HEAT_INDEX) DESC NULLS LAST;
