-- View: Macro trend tagging — cross-category narrative themes
-- Database: MCC_PRESENTATION.TREND_AGENT
--
-- Many-to-many mapping of trends to macro trend narratives. Each trend can
-- appear in 1-3 macro trends. Macro trends span multiple categories and
-- represent broad cultural/commercial themes for editorial and sponsor targeting.
--
-- Usage:
--   SELECT * FROM V_TREND_MACROTRENDS WHERE MACROTREND_NAME = 'Biohacking The Everyday';
--   SELECT MACROTREND_NAME, COUNT(*) FROM V_TREND_MACROTRENDS GROUP BY 1 ORDER BY 2 DESC;

CREATE OR REPLACE VIEW MCC_PRESENTATION.TREND_AGENT.V_TREND_MACROTRENDS AS
SELECT
    mt.MACROTREND_NAME,
    dm.DESCRIPTION              AS MACROTREND_DESCRIPTION,
    dm.TREND_COUNT              AS MACROTREND_SIZE,
    m.TREND_ID,
    COALESCE(d.TREND_NAME, m.TREND_TOPIC) AS TREND_NAME,
    d.CATEGORY,
    d.SUBCATEGORY,
    mt.RELEVANCE_SCORE,
    m.TREND_HEAT_INDEX,
    m.VELOCITY_DIRECTION,
    d.TREND_COMMERCIAL_SCORE
FROM MCC_PRESENTATION.TREND_AGENT.MAP_TREND_MACROTRENDS mt
JOIN MCC_PRESENTATION.TREND_AGENT.DIM_MACROTRENDS dm
    ON mt.MACROTREND_NAME = dm.MACROTREND_NAME
JOIN MCC_PRESENTATION.TREND_AGENT.FCT_TREND_METRICS m
    ON mt.TREND_ID = m.TREND_ID
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.DIM_TREND_ENRICHMENT d
    ON mt.TREND_ID = d.TREND_ID
ORDER BY mt.MACROTREND_NAME, mt.RELEVANCE_SCORE DESC;
