-- View: Macrotrends — trend memberships in macro-trend buckets
-- Database: MCC_PRESENTATION.TREND_AGENT
--
-- Source-first update (2026-04-10):
--   * TREND_COMMERCIAL_SCORE removed (column dropped from DIM)
--   * TREND_NAME coalesces d.TREND_NAME_B2C → d.TREND_NAME_B2B → m.TREND_TOPIC

CREATE OR REPLACE VIEW MCC_PRESENTATION.TREND_AGENT.V_TREND_MACROTRENDS AS
SELECT
    mt.MACROTREND_NAME,
    dm.DESCRIPTION                                              AS MACROTREND_DESCRIPTION,
    dm.TREND_COUNT                                              AS MACROTREND_SIZE,
    m.TREND_ID,
    COALESCE(d.TREND_NAME_B2C, d.TREND_NAME_B2B, m.TREND_TOPIC) AS TREND_NAME,
    d.CATEGORY,
    d.SUBCATEGORY,
    mt.RELEVANCE_SCORE,
    m.TREND_HEAT_INDEX,
    m.VELOCITY_DIRECTION
FROM MCC_PRESENTATION.TREND_AGENT.MAP_TREND_MACROTRENDS mt
JOIN MCC_PRESENTATION.TREND_AGENT.DIM_MACROTRENDS dm
    ON mt.MACROTREND_NAME = dm.MACROTREND_NAME
JOIN MCC_PRESENTATION.TREND_AGENT.FCT_TREND_METRICS m
    ON mt.TREND_ID = m.TREND_ID
LEFT JOIN MCC_PRESENTATION.TREND_AGENT.V_TREND_ENRICHMENT_CURRENT d
    ON mt.TREND_ID = d.TREND_ID
ORDER BY mt.MACROTREND_NAME, mt.RELEVANCE_SCORE DESC;
